### ISSUE TITLE
no alignment generated

### ISSUE THREAD

**Issue by eltonjrv** [vetmohit89/NanoPsiPy#3]
Hello,

Thanks for the tool!
I'm encountering a problem on the NanoPsiPy_estimation step. It seems that the alignment outputs are not generated, as the "alignment" folder contains only an empty features.csv file, and no "plus_strand" nor "minus_strand" subfolders.

$ NanoPsiPy_estimation -i ../rawData/pus1ko/pus1ko-r1/20240228_1330_MC-116134_FAY49401_30e62174/fastq_pass/ -r ../../refGenome/GQ994935.fasta -o pus1ko_estimation.tsv -s treatment

[M::mm_idx_gen::0.016*1.16] collected minimizers
[M::mm_idx_gen::0.026*1.82] sorted minimizers
[M::main::0.027*1.79] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.029*1.73] mid_occ = 26
[M::mm_idx_stat] kmer size: 14; skip: 5; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.031*1.68] distinct minimizers: 45492 (99.22% are singletons); average occurrences: 1.027; average spacing: 2.957; total leng
th: 138146
[M::main] Version: 2.18-r1015
[M::main] CMD: minimap2 -ax splice -uf -k14 --secondary=no/../../refGenome/GQ994935 .psu/nanoPsiPy-run/temp/all_pass_fastq.fastq
[M::main] Real time: 0.038 sec; CPU: 0.057 sec; Peak RSS: 0.008 GB

Traceback (most recent call last):
  File "/nobackup/fbsev/bioinformatics-tools/miniconda3/envs/nanoPsiPy/bin/NanoPsiPy_estimation", line 48, in <module>
    ex_fe()
  File "/nobackup/fbsev/bioinformatics-tools/miniconda3/envs/nanoPsiPy/lib/python3.11/site-packages/NanoPsiPy/Pseudo_U_estimation.py", line 105, in ex_fe
    with open(plus_file, "r") as input_file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.psu/nanoPsiPy-run/alignment/plus_strand/collect_pile_no_intron.txt'

Any light to shed?
Thanks

**Comment by vetmohit89** [comment]
Have you tested the pipeline with test dataset? I have provided MALAT1 RNA treated with PUS7 enzyme fastq files and MALAT1 sequence.

Try running NanoPsiPy_estimation with this dataset first.

Thank you
Mohit

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Elton Vasconcelos ***@***.***>
Sent: Wednesday, May 8, 2024 9:06:15 AM
To: vetmohit89/NanoPsiPy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vetmohit89/NanoPsiPy] no alignment generated (Issue #3)


Hello,

Thanks for the tool!
I'm encountering a problem on the NanoPsiPy_estimation step. It seems that the alignment outputs are not generated, as the "alignment" folder contains only an empty features.csv file, and no "plus_strand" nor "minus_strand" subfolders.

$ NanoPsiPy_estimation -i ../rawData/pus1ko/pus1ko-r1/20240228_1330_MC-116134_FAY49401_30e62174/fastq_pass/ -r ../../refGenome/GQ994935.fasta -o pus1ko_estimation.tsv -s treatment

[M::mm_idx_gen::0.0161.16] collected minimizers
[M::mm_idx_gen::0.0261.82] sorted minimizers
[M::main::0.0271.79] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.0291.73] mid_occ = 26
[M::mm_idx_stat] kmer size: 14; skip: 5; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.031*1.68] distinct minimizers: 45492 (99.22% are singletons); average occurrences: 1.027; average spacing: 2.957; total leng
th: 138146
[M::main] Version: 2.18-r1015
[M::main] CMD: minimap2 -ax splice -uf -k14 --secondary=no/../../refGenome/GQ994935 .psu/nanoPsiPy-run/temp/all_pass_fastq.fastq
[M::main] Real time: 0.038 sec; CPU: 0.057 sec; Peak RSS: 0.008 GB

Traceback (most recent call last):
File "/nobackup/fbsev/bioinformatics-tools/miniconda3/envs/nanoPsiPy/bin/NanoPsiPy_estimation", line 48, in
ex_fe()
File "/nobackup/fbsev/bioinformatics-tools/miniconda3/envs/nanoPsiPy/lib/python3.11/site-packages/NanoPsiPy/Pseudo_U_estimation.py<https://urldefense.com/v3/__http://Pseudo_U_estimation.py__;!!NoSwA-eRAg!BDNGY-FpuwBvxHECYeE6a6Vx8_1wv20UbzemqEjbLgNEHhhjdPboX1yUUAqFcbYtU-Y3tMPh2K_WOK0Ky0t7wu4N$>", line 105, in ex_fe
with open(plus_file, "r") as input_file:
^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.psu/nanoPsiPy-run/alignment/plus_strand/collect_pile_no_intron.txt'

Any light to shed?
Thanks

**Comment by eltonjrv** [comment]
Thanks for your prompt reply.
Sorry, my bad! It's working now after I've gunzipped the fastq files.
Feel free to close this issue.
I'll be running the next steps from your tutorial later today, and will get in further contact if any other issue arises (hopefully not).
Thanks again

**Comment by vetmohit89** [comment]
You're welcome! Glad to hear it's working now. If you have any further questions, please re-open this issue again. 

Thanks
